/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/csrf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCsrfToken"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listSessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sessions/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["revokeSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logoutAll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateCurrentUser"];
        trace?: never;
    };
    "/me/deletion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Requires recent authentication and an idempotency key. */
        post: operations["scheduleAccountDeletion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/deletion/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cancelAccountDeletion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listWorkspaces"];
        put?: never;
        post: operations["createWorkspace"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["bootstrapPersonalWorkspace"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces/{workspaceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description Requires recent authentication and an idempotency key. */
        delete: operations["trashWorkspace"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces/{workspaceId}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["restoreWorkspace"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces/{workspaceId}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listMembers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces/{workspaceId}/members/{memberId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateMember"];
        trace?: never;
    };
    "/workspaces/{workspaceId}/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invitations/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["acceptInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces/{workspaceId}/ownership": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Requires recent authentication. */
        post: operations["transferOwnership"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces/{workspaceId}/budget-policy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getBudgetPolicy"];
        put: operations["updateBudgetPolicy"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces/{workspaceId}/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listProjects"];
        put?: never;
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getProject"];
        put: operations["updateProject"];
        post?: never;
        delete: operations["trashProject"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["archiveProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["restoreProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/duplicate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["duplicateProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Immutable project version history. */
        get: operations["listProjectVersions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/project-templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listProjectTemplates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces/{workspaceId}/project-templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createProjectTemplate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/project-templates/{templateId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateProjectTemplate"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces/{workspaceId}/libraries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listLibraries"];
        put?: never;
        post: operations["createLibrary"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/libraries/{libraryId}/entities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listLibraryEntities"];
        put?: never;
        post: operations["createLibraryEntity"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/library-entities/{entityId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateLibraryEntity"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/library-entities/{entityId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["setLibraryEntityStatus"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/library-links": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["linkProjectLibraryEntity"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces/{workspaceId}/media/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createMediaUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/uploads/{assetId}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["uploadMediaContent"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/uploads/{assetId}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["completeMediaUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces/{workspaceId}/audit-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAuditEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Problem: {
            /** Format: uri */
            type: string;
            title: string;
            status: number;
            code: string;
            detail: string;
        };
        SessionExchange: {
            idToken: string;
            deviceLabel?: string;
        };
        User: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            emailVerified: boolean;
            displayName: string;
            /** Format: uri */
            avatarUrl?: string | null;
            locale: string;
            timezone: string;
            /** Format: uuid */
            personalWorkspaceId?: string | null;
            /** Format: date-time */
            deletionScheduledAt?: string | null;
            /** Format: int64 */
            version: number;
        };
        ProfileUpdate: {
            displayName: string;
            /** Format: uri */
            avatarUrl?: string | null;
            locale: string;
            timezone: string;
        };
        AccountSession: {
            /** Format: uuid */
            id: string;
            deviceLabel: string;
            location?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            lastSeenAt: string;
            /** Format: date-time */
            expiresAt: string;
            current?: boolean;
        };
        SessionList: {
            items: components["schemas"]["AccountSession"][];
        };
        AccountDeletionRequest: {
            /** Format: date-time */
            scheduledAt: string;
            /** Format: date-time */
            purgeAt: string;
        };
        Workspace: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            /** @enum {string} */
            kind: "personal" | "team";
            /** Format: uuid */
            ownerUserId: string;
            /**
             * @default active
             * @enum {string}
             */
            status: "active" | "trashed";
            /** Format: int64 */
            version: number;
        };
        /** @enum {string} */
        Role: "owner" | "admin" | "editor" | "reviewer" | "viewer";
        Membership: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            workspaceId: string;
            /** Format: uuid */
            userId: string;
            /** Format: email */
            email?: string;
            displayName?: string;
            role: components["schemas"]["Role"];
            /** @enum {string} */
            status: "active" | "removed";
            canSpend: boolean;
            /** Format: int64 */
            monthlyLimitMicros?: number | null;
            /** Format: int64 */
            perRunLimitMicros?: number | null;
        };
        MemberUpdate: {
            role?: components["schemas"]["Role"];
            canSpend?: boolean;
            /** Format: int64 */
            monthlyLimitMicros?: number | null;
            /** Format: int64 */
            perRunLimitMicros?: number | null;
            remove?: boolean;
        };
        InvitationCreate: {
            /** Format: email */
            email: string;
            role: components["schemas"]["Role"];
        };
        Invitation: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            workspaceId: string;
            /** Format: email */
            email: string;
            role: components["schemas"]["Role"];
            /** Format: date-time */
            expiresAt: string;
            developmentToken?: string | null;
        };
        BudgetPolicy: {
            /** Format: uuid */
            workspaceId: string;
            /** @default USD */
            currency: string;
            /** Format: int64 */
            monthlyLimitMicros?: number | null;
            /** Format: int64 */
            perRunApprovalThresholdMicros?: number | null;
            /** Format: int64 */
            version: number;
        };
        BudgetPolicyUpdate: {
            /** @default USD */
            currency: string;
            /** Format: int64 */
            monthlyLimitMicros?: number | null;
            /** Format: int64 */
            perRunApprovalThresholdMicros?: number | null;
        };
        /** @enum {string} */
        ProductionFormat: "short_film" | "feature" | "episodic" | "music_video" | "advertisement" | "trailer" | "other";
        ProjectSettings: {
            name: string;
            /** @enum {string} */
            projectType: "single" | "series";
            productionFormat: components["schemas"]["ProductionFormat"];
            /** @default 16 */
            aspectWidth: number;
            /** @default 9 */
            aspectHeight: number;
            /** @default 24 */
            frameRateNumerator: number;
            /** @default 1 */
            frameRateDenominator: number;
            /** @default en */
            audioLanguage: string;
            /**
             * @default moderate
             * @enum {string}
             */
            rating: "family" | "moderate" | "mature";
            /** @default  */
            styleDirection: string;
            /**
             * @default balanced
             * @enum {string}
             */
            qualityPolicy: "draft" | "balanced" | "final";
            /** Format: int64 */
            costCeilingMicros?: number | null;
        };
        Project: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            workspaceId: string;
            slug: string;
            /** @enum {string} */
            status: "active" | "archived" | "trashed";
            /** @constant */
            privacy: "private";
            /** Format: int64 */
            currentVersion: number;
            settings: components["schemas"]["ProjectSettings"];
            /** Format: date-time */
            deletedAt?: string | null;
            /** Format: date-time */
            purgeAt?: string | null;
        };
        ProjectVersion: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            projectId: string;
            /** Format: int64 */
            version: number;
            settings: components["schemas"]["ProjectSettings"];
            /** Format: date-time */
            createdAt: string;
        };
        ProjectTemplateInput: {
            name: string;
            description?: string;
            settings: components["schemas"]["ProjectSettings"];
        };
        ProjectTemplate: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            workspaceId?: string | null;
            name: string;
            description?: string;
            system: boolean;
            /** Format: int64 */
            currentVersion: number;
            settings: components["schemas"]["ProjectSettings"];
        };
        Library: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            workspaceId: string;
            name: string;
            /** @enum {string} */
            type: "story" | "brand";
            /** Format: date-time */
            archivedAt?: string | null;
            /** Format: int64 */
            version: number;
        };
        /** @enum {string} */
        EntityType: "character" | "location" | "prop" | "faction" | "creature" | "vehicle" | "style_guide" | "voice_profile" | "other";
        LibraryEntityInput: {
            name: string;
            type: components["schemas"]["EntityType"];
            aliases?: string[];
            summary?: string;
            description?: string;
            tags?: string[];
            attributes?: {
                [key: string]: unknown;
            };
            changeSummary?: string;
            mediaAssetVersionIds?: string[];
        };
        LibraryEntityVersion: components["schemas"]["LibraryEntityInput"] & {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            entityId: string;
            /** Format: int64 */
            version: number;
            /** @enum {string} */
            status: "draft" | "approved" | "retired";
            /** Format: uuid */
            sourceVersionId?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        LibraryEntity: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            workspaceId: string;
            /** Format: uuid */
            libraryId: string;
            /** Format: uuid */
            currentVersionId: string;
            currentVersion: components["schemas"]["LibraryEntityVersion"];
        };
        ProjectLibraryLink: {
            /** Format: uuid */
            projectId: string;
            /** Format: uuid */
            entityVersionId: string;
            /** Format: date-time */
            linkedAt?: string;
        };
        /** @enum {string} */
        ProcessingState: "authorized" | "uploaded" | "processing" | "ready" | "rejected";
        /** @enum {string} */
        MediaKind: "image" | "video" | "audio" | "voice" | "3d";
        UploadRequest: {
            kind: components["schemas"]["MediaKind"];
            filename: string;
            contentType: string;
            /** Format: int64 */
            sizeBytes: number;
            checksumSha256?: string | null;
        };
        MediaAsset: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            workspaceId: string;
            kind: components["schemas"]["MediaKind"];
            filename: string;
            contentType: string;
            /** Format: int64 */
            sizeBytes: number;
            checksumSha256?: string | null;
            state: components["schemas"]["ProcessingState"];
            rejectionReason?: string | null;
        };
        MediaAssetVersion: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            assetId: string;
            /** Format: int64 */
            version: number;
            objectPath: string;
            previewObjectPath?: string | null;
            metadata: {
                [key: string]: unknown;
            };
        };
        UploadSession: {
            asset: components["schemas"]["MediaAsset"];
            uploadUrl: string;
            expiresInSeconds: number;
        };
        UploadAuthorization: components["schemas"]["UploadSession"];
        AuditEvent: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            workspaceId?: string | null;
            /** Format: uuid */
            actorUserId?: string | null;
            targetType?: string | null;
            /** Format: uuid */
            targetId?: string | null;
            action: string;
            metadata?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            createdAt: string;
        };
    };
    responses: {
        /** @description RFC 9457 problem details. */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        WorkspaceId: string;
        ProjectId: string;
        SessionId: string;
        MemberId: string;
        LibraryId: string;
        EntityId: string;
        TemplateId: string;
        AssetId: string;
        IfMatch: string;
        CsrfToken: string;
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getCsrfToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CSRF token and matching readable cookie. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        csrfToken: string;
                    };
                };
            };
        };
    };
    createSession: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionExchange"];
            };
        };
        responses: {
            /** @description Session established. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        user: components["schemas"]["User"];
                        /** Format: uuid */
                        sessionId: string;
                        requiresVerification: boolean;
                    };
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active account sessions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionList"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    revokeSession: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    logoutAll: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All sessions revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    updateCurrentUser: {
        parameters: {
            query?: never;
            header: {
                "If-Match": components["parameters"]["IfMatch"];
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileUpdate"];
            };
        };
        responses: {
            /** @description Updated profile. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    scheduleAccountDeletion: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deletion scheduled. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountDeletionRequest"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    cancelAccountDeletion: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deletion cancelled */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    listWorkspaces: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Workspaces visible to the caller. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Workspace"][];
                    };
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createWorkspace: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                };
            };
        };
        responses: {
            /** @description Team workspace created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    bootstrapPersonalWorkspace: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Existing or newly created personal workspace. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    trashWorkspace: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Workspace moved to trash lifecycle */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    restoreWorkspace: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Workspace restored */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    listMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Workspace memberships. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Membership"][];
                    };
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    updateMember: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
                memberId: components["parameters"]["MemberId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberUpdate"];
            };
        };
        responses: {
            /** @description Updated membership. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Membership"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createInvitation: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvitationCreate"];
            };
        };
        responses: {
            /** @description Invitation created and mailed. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Invitation"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    acceptInvitation: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    token: string;
                };
            };
        };
        responses: {
            /** @description Invitation accepted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    transferOwnership: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    memberId: string;
                };
            };
        };
        responses: {
            /** @description Ownership transferred */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    getBudgetPolicy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Workspace spend policy. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BudgetPolicy"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    updateBudgetPolicy: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BudgetPolicyUpdate"];
            };
        };
        responses: {
            /** @description Updated spend policy. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BudgetPolicy"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listProjects: {
        parameters: {
            query?: {
                status?: "active" | "archived" | "trashed";
                q?: string;
            };
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Projects. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Project"][];
                    };
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectSettings"];
            };
        };
        responses: {
            /** @description Project created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    updateProject: {
        parameters: {
            query?: never;
            header: {
                "If-Match": components["parameters"]["IfMatch"];
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectSettings"];
            };
        };
        responses: {
            /** @description Project updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    trashProject: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project moved to trash. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    archiveProject: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project archived. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    restoreProject: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project restored. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    duplicateProject: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    name?: string;
                };
            };
        };
        responses: {
            /** @description Duplicate created in the same workspace. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listProjectVersions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project versions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["ProjectVersion"][];
                    };
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listProjectTemplates: {
        parameters: {
            query?: {
                workspaceId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description System and workspace templates. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["ProjectTemplate"][];
                    };
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createProjectTemplate: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectTemplateInput"];
            };
        };
        responses: {
            /** @description Workspace template saved. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectTemplate"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    updateProjectTemplate: {
        parameters: {
            query?: never;
            header: {
                "If-Match": components["parameters"]["IfMatch"];
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                templateId: components["parameters"]["TemplateId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectTemplateInput"];
            };
        };
        responses: {
            /** @description Template version updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectTemplate"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listLibraries: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Workspace story/brand libraries. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Library"][];
                    };
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createLibrary: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    /** @enum {string} */
                    type: "story" | "brand";
                };
            };
        };
        responses: {
            /** @description Library created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Library"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listLibraryEntities: {
        parameters: {
            query?: {
                q?: string;
                type?: components["schemas"]["EntityType"];
                status?: "draft" | "approved" | "retired";
            };
            header?: never;
            path: {
                libraryId: components["parameters"]["LibraryId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Library entities. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["LibraryEntity"][];
                    };
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createLibraryEntity: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                libraryId: components["parameters"]["LibraryId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LibraryEntityInput"];
            };
        };
        responses: {
            /** @description Draft entity version created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryEntity"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    updateLibraryEntity: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                entityId: components["parameters"]["EntityId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LibraryEntityInput"];
            };
        };
        responses: {
            /** @description New draft version created. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryEntity"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    setLibraryEntityStatus: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                entityId: components["parameters"]["EntityId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    status: "approved" | "retired";
                };
            };
        };
        responses: {
            /** @description Version status updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryEntity"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    linkProjectLibraryEntity: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    entityVersionId: string;
                };
            };
        };
        responses: {
            /** @description Project pinned to approved entity version. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectLibraryLink"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createMediaUpload: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UploadRequest"];
            };
        };
        responses: {
            /** @description Upload authorization. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadAuthorization"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    uploadMediaContent: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                assetId: components["parameters"]["AssetId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/octet-stream": string;
                "image/jpeg": string;
                "image/png": string;
                "image/webp": string;
                "video/mp4": string;
                "video/quicktime": string;
                "video/webm": string;
                "audio/wav": string;
                "audio/mpeg": string;
                "audio/mp4": string;
                "audio/flac": string;
                "audio/ogg": string;
                "model/gltf-binary": string;
            };
        };
        responses: {
            /** @description Quarantine upload complete */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    completeMediaUpload: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                assetId: components["parameters"]["AssetId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ingestion workflow started or queued. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaAsset"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listAuditEvents: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Audit events. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["AuditEvent"][];
                    };
                };
            };
            default: components["responses"]["Problem"];
        };
    };
}
